// Comprehensive disposable/temporary email domain blocklist
// Includes 500+ known disposable email services and their variations
const DISPOSABLE_DOMAINS = new Set([
  // Major temp mail services
  "temp-mail.org",
  "temp-mail.io",
  "temp-mail.de",
  "tempmail.com",
  "tempmail.de",
  "tempmail.eu",
  "tempmail.it",
  "tempmail2.com",
  "tempail.com",
  "tempalias.com",
  "tempe4mail.com",
  "tempemail.cc",
  "tempemail.co.za",
  "tempemail.net",
  "tempinbox.com",
  "tempinbox.co.uk",
  "tempmaildemo.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempmailo.com",
  "tempmailaddress.com",
  "tempomail.fr",
  "temporarily.de",
  "temporarioemail.com.br",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "temporarymail.org",
  "tempr.email",
  "tempsky.com",
  "tempthe.net",
  "tmail.com",
  "tmpmail.net",
  "tmpmail.org",
  "mytemp.email",
  "mytemps.email",
  "utempmail.com",

  // Guerrilla Mail network
  "guerrillamail.com",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "grr.la",
  "sharklasers.com",

  // Mailinator network
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailinater.com",
  "mailincubator.com",
  "mailnator.com",
  "notmailinator.com",
  "tmailinator.com",

  // Yopmail network
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yuurok.com",
  "cool.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",

  // Trashmail network
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.at",
  "trashmail.de",
  "trashmail.io",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com",
  "trashymail.net",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash-amil.com",
  "trash2009.com",
  "trashemail.de",
  "trashevil.com",
  "trashevil.de",
  "trashimail.com",
  "trashimail.de",

  // 10-minute / 5-minute mail
  "10minutemail.com",
  "10minutemail.net",
  "5minutemail.com",
  "zehnminutenmail.de",

  // Other major services
  "throwaway.email",
  "throwawayemailaddress.com",
  "dispostable.com",
  "maildrop.cc",
  "fakeinbox.com",
  "getnada.com",
  "emailondeck.com",
  "harakirimail.com",
  "mohmal.com",
  "burnermail.io",
  "mailcatch.com",
  "fakemailgenerator.com",
  "emailfake.com",
  "crazymailing.com",
  "boomlify.com",
  "nexafilm.com",
  "mailnesia.com",
  "mailsac.com",
  "inboxkitten.com",
  "33mail.com",
  "anonaddy.com",
  "altmails.com",
  "emailnax.com",

  // B
  "binkmail.com",
  "bobmail.info",

  // C
  "chammy.info",

  // D
  "devnullmail.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "despam.it",

  // E
  "emailgo.de",
  "emailigo.de",
  "emailtemporaire.com",
  "emailtemporaire.fr",
  "emailtemporario.com.br",
  "emailsensei.com",
  "ephemail.net",
  "et.vg",
  "example.com",

  // F
  "filzmail.com",
  "fixmail.tk",
  "flurred.com",

  // G
  "getairmail.com",
  "get2mail.fr",
  "gishpuppy.com",

  // H
  "haltospam.com",

  // I
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",

  // J
  "jetable.com",
  "jetable.net",
  "jetable.org",

  // K
  "kasmail.com",
  "kurzepost.de",

  // L
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lookugly.com",
  "lortemail.dk",

  // M - mail*
  "mailbidon.com",
  "mailblocks.com",
  "maileater.com",
  "mailexpire.com",
  "mailforspam.com",
  "mailfree.ga",
  "mailfreeonline.com",
  "mailguard.me",
  "mailhazard.com",
  "mailhazard.us",
  "mailhz.me",
  "mailimate.com",
  "mailismagic.com",
  "mailme.ir",
  "mailme.lv",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnull.com",
  "mailorg.org",
  "mailpick.biz",
  "mailrock.biz",
  "mailscrap.com",
  "mailseal.de",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailzilla.com",
  "mbx.cc",
  "meltmail.com",
  "mintemail.com",
  "msgos.com",
  "mwarner.org",
  "mx0.wwwnew.eu",

  // N
  "neverbox.com",
  "no-spam.ws",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.ch",
  "nomail2me.com",
  "notsomuch.com",
  "nowmymail.com",

  // O
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "oneoffemail.com",
  "onewaymail.com",
  "oopi.org",
  "ordinaryamerican.net",
  "owlpic.com",

  // P
  "pjjkp.com",
  "plexolan.de",
  "pookmail.com",
  "privacy.net",
  "proxymail.eu",
  "putthisinyouremail.com",

  // Q
  "quickinbox.com",

  // R
  "rcpt.at",
  "reallymymail.com",
  "receiveee.com",
  "recode.me",
  "regbypass.com",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",

  // S - s0-sh
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "scbox.one.pl",
  "selfdestructingmail.com",
  "shieldemail.com",
  "shieldedmail.com",
  "shiftmail.com",
  "sinnlos-mail.de",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "smashmail.de",
  "sogetthis.com",
  "soodonims.com",

  // S - spam*
  "spam.la",
  "spam.su",
  "spam4.me",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.us",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf",
  "spamfighter.ga",
  "spamfighter.gq",
  "spamfighter.ml",
  "spamfighter.tk",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamgourmet.com",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrap.ro",
  "spamtrail.com",

  // S - su-sy
  "superrito.com",
  "suremail.info",

  // T - th
  "thankmail.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "tittbit.in",
  "tradermail.info",
  "turual.com",
  "twinmail.de",
  "tyldd.com",

  // U
  "uggsrock.com",
  "upliftnow.com",
  "uplipht.com",

  // V
  "venompen.com",
  "veryreallyme.com",
  "veryreallymymail.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",

  // W
  "wasteland.rfc822.org",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfemail.net",
  "wegwerfemail.org",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
  "whatiaas.com",
  "whatpaas.com",
  "whyspam.me",
  "wikidocuslice.com",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "wwwnew.eu",

  // X
  "x1x.spyi.ru",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xoxy.net",

  // Y
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",

  // Z
  "za.com",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",

  // Additional widely-used disposable services
  "disposableemailaddresses.emailmiser.com",
  "qq.com",
  "mailtemp.net",
  "tempmailaddress.com",
  "tempmaildemo.com",
  "anonbox.net",
  "anonymbox.com",
  "antichef.com",
  "antichef.net",
  "baxomale.ht.cx",
  "beefmilk.com",
  "bofthew.com",
  "bugmenot.com",
  "bumpymail.com",
  "casualdx.com",
  "centermail.com",
  "centermail.net",
  "chogmail.com",
  "choicemail1.com",
  "clipmail.eu",
  "coldemail.info",
  "consumerriot.com",
  "coolimpool.org",
  "correo.blogos.net",
  "cosmorph.com",
  "courrieltemporaire.com",
  "cubiclink.com",
  "curryworld.de",
  "cust.in",
  "dacoolest.com",
  "dandikmail.com",
  "dayrep.com",
  "deadaddress.com",
  "deadfake.cf",
  "deadfake.ga",
  "deadfake.ml",
  "deadfake.tk",
  "deadspam.com",
  "dealja.com",
  "despammed.com",
  "devnullmail.de",
  "dfgh.net",
  "digitalsanctuary.com",
  "dingbone.com",
  "dingfone.com",
  "disposable.cf",
  "disposable.ga",
  "disposable.ml",
  "disposableaddress.com",
  "disposableinbox.com",
  "dispose.it",
  "dispomail.eu",
  "dm.w3internet.co.uk",
  "dodgeit.com",
  "dodgit.com",
  "dodgit.org",
  "donemail.ru",
  "dontreg.com",
  "dontsendmespam.de",
  "drdrb.com",
  "drdrb.net",
  "droplar.com",
  "dropmail.me",
  "duam.net",
  "dudmail.com",
  "dumpandjunk.com",
  "dumpmail.de",
  "dumpyemail.com",
  "e4ward.com",
  "easytrashmail.com",
  "einmalmail.de",
  "einrot.com",
  "einrot.de",
  "eintagsmail.de",
  "email-fake.cf",
  "email-fake.ga",
  "email-fake.gq",
  "email-fake.ml",
  "email-fake.tk",
  "email60.com",
  "emaildienst.de",
  "emailfake.com",
  "emailisvalid.com",
  "emailmiser.com",
  "emailproxsy.com",
  "emails.ga",
  "emailspam.cf",
  "emailspam.ga",
  "emailspam.gq",
  "emailspam.ml",
  "emailspam.tk",
  "emailthe.net",
  "emailto.de",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emz.net",
  "enterto.com",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "eyepaste.com",
  "fakedemail.com",
  "fakeinformation.com",
  "fakemail.fr",
  "fakemailz.com",
  "fammix.com",
  "fansworldwide.de",
  "fantasymail.de",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "fightallspam.com",
  "fiifke.de",
  "filzmail.com",
  "fivemail.de",
  "fixmail.tk",
  "fizmail.com",
  "fleckens.hu",
  "flyspam.com",
  "footard.com",
  "forgetmail.com",
  "fr33mail.info",
  "frapmail.com",
  "front14.org",
  "fux0ringduh.com",
  "garliclife.com",
  "gehensiull.com",
  "get1mail.com",
  "getonemail.com",
  "getonemail.net",
  "ghosttexter.de",
  "girlsundertheinfluence.com",
  "gishpuppy.com",
  "goemailgo.com",
  "gotmail.com",
  "gotmail.net",
  "gotmail.org",
  "gotti.otherinbox.com",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "grandmamail.com",
  "grandmasmail.com",
  "great-host.in",
  "greensloth.com",
  "greyspaceship.com",
  "gsrv.co.uk",
  "guerrillamail.com",
  "h8s.org",
  "hacccc.com",
  "haltospam.com",
  "hartbot.de",
  "hatespam.org",
  "hellodream.mobi",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hiru-dea.com",
  "hochsydney.com",
  "hotpop.com",
  "hulapla.de",
  "ichimail.com",
  "imails.info",
  "inbax.tk",
  "inbox.si",
  "inboxalias.com",
  "inboxclean.com",
  "inboxclean.org",
  "inboxproxy.com",
  "incognitomail.com",
  "insanumingeniumhominis.com",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  "jetable.com",
  "jnxjn.com",
  "jourrapide.com",
  "junk1e.com",
  "junkmail.ga",
  "junkmail.gq",
  "keepmymail.com",
  "killmail.com",
  "killmail.net",
  "kingsq.ga",
  "kiois.com",
  "klassmaster.com",
  "klassmaster.net",
  "klzlk.com",
  "koszmail.pl",
  "kulturbetrieb.info",
  "lackmail.net",
  "lakelivingston.com",
  "landmail.co",
  "lastmail.co",
  "lavabit.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "libox.fr",
  "lol.ovpn.to",
  "lolfreak.net",
  "lookugly.com",
  "lopl.co.cc",
  "lortemail.dk",
  "lovemeleaveme.com",
  "lr78.com",
  "lroid.com",
  "lukop.dk",
  "m21.cc",
  "mail-hierarchie.de",
  "mail-temporaire.fr",
  "mail.by",
  "mail.mezimages.net",
  "mail.zp.ua",
  "mail2rss.org",
  "mail333.com",
  "mail4trash.com",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailcat.biz",
  "mailcatch.com",
  "mailde.de",
  "mailde.info",
  "maildx.com",
  "mailfa.tk",
  "mailfree.ga",
  "mailfreeonline.com",
  "mailfs.com",
  "mailguard.me",
  "mailhazard.com",
  "mailhazard.us",
  "mailhz.me",
  "mailimate.com",
  "mailin8r.com",
  "mailinater.com",
  "mailismagic.com",
  "mailmate.com",
  "mailme24.com",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnull.com",
  "mailorg.org",
  "mailpick.biz",
  "mailquack.com",
  "mailrock.biz",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailzilla.com",
  "makemetheking.com",
  "manifestgenerator.com",
  "manybrain.com",
  "mbx.cc",
  "meinspamschutz.de",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "mfsa.ru",
  "mierdamail.com",
  "migmail.pl",
  "migumail.com",
  "mintemail.com",
  "misterpinball.de",
  "mmmmail.com",
  "moakt.com",
  "mobi.web.id",
  "mobileninja.co.uk",
  "mohmal.com",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "monumentmail.com",
  "msa.minsmail.com",
  "mt2015.com",
  "mx0.wwwnew.eu",
  "my10telemail.com",
  "mycleaninbox.net",
  "myemailboxy.com",
  "mymailoasis.com",
  "mynetstore.de",
  "mypartyclip.de",
  "myphantom.com",
  "mysamp.de",
  "myspaceinc.com",
  "myspaceinc.net",
  "myspaceinc.org",
  "myspacepimpedup.com",
  "mytemp.email",
  "mytemps.email",
  "mytrashmail.com",
  "nabala.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtansen.de",
  "netmails.com",
  "netmails.net",
  "netzidiot.de",
  "neverbox.com",
  "no-spam.ws",
  "noblepioneer.com",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.ch",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nonspam.eu",
  "nonspammer.de",
  "noref.in",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "nospamthanks.info",
  "nothingtoseehere.ca",
  "notmailinator.com",
  "notsomuch.com",
  "nowmymail.com",
  "nurfuerspam.de",
  "nus.edu.sg",
  "nwytg.net",
  "objectmail.com",
  "obobbo.com",
  "odaymail.com",
  "odnorazovoe.ru",
  "oneoffemail.com",
  "onewaymail.com",
  "onlatedotcom.info",
  "online.ms",
  "oopi.org",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pimpedupmyspace.com",
  "pjjkp.com",
  "plexolan.de",
  "pookmail.com",
  "privacy.net",
  "proxymail.eu",
  "prtnx.com",
  "punkass.com",
  "putthisinyouremail.com",
  "qq.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "recursor.net",
  "regbypass.com",
  "rejectmail.com",
  "reliable-mail.com",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "scatmail.com",
  "scbox.one.pl",
  "schafmail.de",
  "selfdestructingmail.com",
  "selfdestructingmail.org",
  "sendspamhere.com",
  "sharklasers.com",
  "shieldemail.com",
  "shieldedmail.com",
  "shiftmail.com",
  "shitmail.me",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "siteposter.net",
  "skeefmail.com",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "slowslow.de",
  "smashmail.de",
  "smellrear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakymail.de",
  "snkmail.com",
  "sofimail.com",
  "sogetthis.com",
  "soodonims.com",
  "spam.la",
  "spam.su",
  "spam4.me",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf",
  "spamfighter.ga",
  "spamfighter.gq",
  "spamfighter.ml",
  "spamfighter.tk",
  "spamfree.eu",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrap.ro",
  "spamtrail.com",
  "spamwc.de",
  "superrito.com",
  "suremail.info",
  "teewars.org",
  "teleworm.com",
  "teleworm.us",
  "thankmail.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "throam.com",
  "throwam.com",
  "tittbit.in",
  "tizi.com",
  "tmailinator.com",
  "toiea.com",
  "topranklist.de",
  "tradermail.info",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "upliftnow.com",
  "uplipht.com",
  "venompen.com",
  "veryreallyme.com",
  "veryreallymymail.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcastmedia.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerfadresse.de",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfemail.net",
  "wegwerfemail.org",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wh4f.org",
  "whatiaas.com",
  "whatpaas.com",
  "whyspam.me",
  "wikidocuslice.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "wwwnew.eu",
  "x1x.spyi.ru",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xoxy.net",
  "xyzfree.net",
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yuurok.com",
  "za.com",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",
]);

// Suspicious domain patterns that indicate disposable/temp email services
const SUSPICIOUS_PATTERNS = [
  /^temp/i,
  /^trash/i,
  /^spam/i,
  /^junk/i,
  /^fake/i,
  /^throw/i,
  /^disposable/i,
  /^burner/i,
  /^guerrilla/i,
  /minutemail/i,
  /tempmail/i,
  /mailtemp/i,
  /trashmail/i,
  /wegwerf/i,
  /einweg/i,
  /einmal/i,
  /wegwurf/i,
];

// Known legitimate email providers (allowlist to avoid false positives from heuristics)
const LEGITIMATE_PROVIDERS = new Set([
  "gmail.com",
  "googlemail.com",
  "outlook.com",
  "outlook.fr",
  "outlook.de",
  "outlook.co.uk",
  "hotmail.com",
  "hotmail.fr",
  "hotmail.de",
  "hotmail.co.uk",
  "live.com",
  "live.fr",
  "live.de",
  "live.co.uk",
  "msn.com",
  "yahoo.com",
  "yahoo.fr",
  "yahoo.de",
  "yahoo.co.uk",
  "yahoo.co.jp",
  "ymail.com",
  "protonmail.com",
  "protonmail.ch",
  "proton.me",
  "pm.me",
  "icloud.com",
  "me.com",
  "mac.com",
  "aol.com",
  "zoho.com",
  "zohomail.com",
  "fastmail.com",
  "fastmail.fm",
  "tutanota.com",
  "tuta.io",
  "gmx.com",
  "gmx.de",
  "gmx.net",
  "web.de",
  "mail.com",
  "email.com",
  "usa.com",
  "comcast.net",
  "verizon.net",
  "att.net",
  "sbcglobal.net",
  "bellsouth.net",
  "cox.net",
  "charter.net",
  "earthlink.net",
  "optonline.net",
  "mail.ru",
  "yandex.com",
  "yandex.ru",
  "163.com",
  "126.com",
  "sina.com",
  "rediffmail.com",
]);

/**
 * Heuristic check for domains that look like randomly-generated disposable domains.
 * Catches rotating/new disposable domains not yet in the blocklist.
 */
function looksLikeRandomDomain(domain: string): boolean {
  const name = domain.split(".")[0];
  if (!name || name.length < 4) return false;

  // Count consonant clusters (random strings tend to have unusual letter distributions)
  const consonantClusters = name.match(/[bcdfghjklmnpqrstvwxyz]{4,}/gi);
  if (consonantClusters) return true;

  // High ratio of digits to letters in domain name
  const digits = (name.match(/\d/g) || []).length;
  const letters = (name.match(/[a-z]/gi) || []).length;
  if (letters > 0 && digits / letters > 0.5 && name.length > 6) return true;

  return false;
}

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;

  // Always allow known legitimate providers
  if (LEGITIMATE_PROVIDERS.has(domain)) return false;

  // Check against the blocklist
  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  // Check suspicious domain name patterns
  const domainName = domain.split(".")[0];
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(domainName)) return true;
  }

  // Check for randomly-generated domain names
  if (looksLikeRandomDomain(domain)) return true;

  return false;
}
